Pandas library in Python programming enables data manipulation and analysis with structures like Series and DataFrame.

Series is a one-dimensional labelled array capable of holding any datatype

In [2]:
import pandas as pd  #importing the pandas library

# creating a Series from a Python list
# the output datatype is 'object' because the list contains multiple datatype
s = pd.Series([1, 2, 3, 'Numbers', 4, 5])
print(s)

0          1
1          2
2          3
3    Numbers
4          4
5          5
dtype: object

DataFrame is a two-dimensional labelled data structure with columns similar to a spreadsheet or SQL table

In [3]:
df = {'name':['Magnus','Rachael','Joanna','King'],
      'gender':['Male','Female','Female','Male'],
      'age':[46,32,29,27],
      'location':['Lagos','Port Harcourt','Ottawa','Boston']}
users = pd.DataFrame(df)
print(users)

      name  gender  age       location
0   Magnus    Male   46          Lagos
1  Rachael  Female   32  Port Harcourt
2   Joanna  Female   29         Ottawa
3     King    Male   27         Boston

Data Manipulation

Data in Series and DataFrames can be accessed and manipulated using indexing and slicing

In [4]:
# Index is used to access a single element
print(s[0])
print(users['name'][2])

# Slicing accesses a range of elements
df = pd.DataFrame(users)
df[['name']]

1
Joanna

      name
0   Magnus
1  Rachael
2   Joanna
3     King

Data Combination

This involves joining, merging or concatenating multiple pandas data structure into a single dataset

In [5]:
# Concatenation combines two or more dataframes with similar columns
# either horizontally or vertically
staff_1 = pd.DataFrame({'name':['Peter','Janet','James'],'age':[23,45,32]})
staff_2 = pd.DataFrame({'name':['Lisa','Stacy','Greg'],'age':[42,37,29]})

# Vertical Concatenation(row-wise from top to bottom)
vertical_con = pd.concat([staff_1,staff_2],axis=0,keys=['staff_1','staff_2'])
vertical_con

            name  age
staff_1 0  Peter   23
        1  Janet   45
        2  James   32
staff_2 0   Lisa   42
        1  Stacy   37
        2   Greg   29

In [9]:
# Horizontal Concatenation(column-wise from left to right)
horizontal_con = pd.concat([staff_1,staff_2],axis=1,keys=['staff_1','staff_2'])
horizontal_con

  staff_1     staff_2
     name age    name age
0   Peter  23    Lisa  42
1   Janet  45   Stacy  37
2   James  32    Greg  29

In [10]:
# vertical concatenation by location; first row
vertical_con.loc['staff_1', 0]

name    Peter
age        23
Name: (staff_1, 0), dtype: object

In [15]:
# vertical concatenation by location; first row,first column
vertical_con.loc['staff_1', 0][0]

/tmp/ipykernel_239/3624815216.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  vertical_con.loc['staff_1', 0][0]

'Peter'

In [16]:
vertical_con.loc['staff_1', 0]['name':'age']

name    Peter
age        23
Name: (staff_1, 0), dtype: object

In [17]:
# Vertical Concatenation ignoring the names of the combined dataframes
vertical_con = pd.concat([staff_1,staff_2],axis=0, ignore_index=True)
vertical_con

    name  age
0  Peter   23
1  Janet   45
2  James   32
3   Lisa   42
4  Stacy   37
5   Greg   29