Pandas library in Python programming enables data manipulation and analysis with structures like Series and DataFrame.

Series is a one-dimensional labelled array capable of holding any datatype

In [1]:
import pandas as pd  #importing the pandas library

# creating a Series from a Python list
# the output datatype is 'object' because the list contains multiple datatype
s = pd.Series([1, 2, 3, 'Numbers', 4, 5])
print(s)

0          1
1          2
2          3
3    Numbers
4          4
5          5
dtype: object

DataFrame is a two-dimensional labelled data structure with columns similar to a spreadsheet or SQL table

In [2]:
df = {'name':['Magnus','Rachael','Joanna','King'],
      'gender':['Male','Female','Female','Male'],
      'age':[46,32,29,27],
      'location':['Lagos','Port Harcourt','Ottawa','Boston']}
users = pd.DataFrame(df)
print(users)

      name  gender  age       location
0   Magnus    Male   46          Lagos
1  Rachael  Female   32  Port Harcourt
2   Joanna  Female   29         Ottawa
3     King    Male   27         Boston

Data Manipulation

Data in Series and DataFrames can be accessed and manipulated using indexing and slicing

In [3]:
# Index is used to access a single element
print(s[0])
print(users['name'][2])

# Slicing accesses a range of elements
df = pd.DataFrame(users)
df[['name']]

1
Joanna

      name
0   Magnus
1  Rachael
2   Joanna
3     King

Data Combination

This involves joining, merging or concatenating multiple pandas data structure into a single dataset

In [4]:
# Concatenation combines two or more dataframes with similar columns
# either horizontally or vertically
staff_1 = pd.DataFrame({'name':['Peter','Janet','James'],'age':[23,45,32]})
staff_2 = pd.DataFrame({'name':['Lisa','Stacy','Greg'],'age':[42,37,29]})

# Vertical Concatenation(row-wise from top to bottom)
vertical_con = pd.concat([staff_1,staff_2],axis=0,keys=['staff_1','staff_2'])
vertical_con

            name  age
staff_1 0  Peter   23
        1  Janet   45
        2  James   32
staff_2 0   Lisa   42
        1  Stacy   37
        2   Greg   29

In [5]:
# vertical concatenation by location; first row
vertical_con.loc['staff_1', 0]

name    Peter
age        23
Name: (staff_1, 0), dtype: object

In [6]:
# vertical concatenation by location; first row,first column
vertical_con.loc['staff_1', 0][0]

/tmp/ipykernel_431/3624815216.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  vertical_con.loc['staff_1', 0][0]

'Peter'

In [7]:
vertical_con.loc['staff_1', 0]['name':'age']

name    Peter
age        23
Name: (staff_1, 0), dtype: object

In [8]:
# Vertical Concatenation ignoring the names of the combined dataframes
vertical_con = pd.concat([staff_1,staff_2],axis=0, ignore_index=True)
vertical_con

    name  age
0  Peter   23
1  Janet   45
2  James   32
3   Lisa   42
4  Stacy   37
5   Greg   29

In [9]:
# Horizontal Concatenation(column-wise from left to right)
horizontal_con = pd.concat([staff_1,staff_2],axis=1,keys=['staff_1','staff_2'])
horizontal_con

  staff_1     staff_2
     name age    name age
0   Peter  23    Lisa  42
1   Janet  45   Stacy  37
2   James  32    Greg  29

In [10]:
horizontal_con["staff_1"]

    name  age
0  Peter   23
1  Janet   45
2  James   32

In [11]:
horizontal_con["staff_2"]

    name  age
0   Lisa   42
1  Stacy   37
2   Greg   29

In [12]:
horizontal_con["staff_1"][["name"]]

    name
0  Peter
1  Janet
2  James

MERGE

The merge function is used to combine two or more dataframes based on a common column(s)

In [13]:
df_3 = pd.DataFrame({'Names': ['Ama', 'Barry', 'Celestine', 'Dela'], 'Score1': [1, 2, 3, 4]})
df_4 = pd.DataFrame({'Names': ['Barry', 'Dela', 'Emma', 'Frank'], 'Score2': [5, 6, 7, 8]})

In [14]:
# keeps records of 'Names' common to both dataframes
pd.merge(df_3, df_4, on='Names', how='inner')

   Names  Score1  Score2
0  Barry       2       5
1   Dela       4       6

In [15]:
# keeps all records from both dataframes
pd.merge(df_3, df_4, on='Names', how='outer')

       Names  Score1  Score2
0        Ama     1.0     NaN
1      Barry     2.0     5.0
2  Celestine     3.0     NaN
3       Dela     4.0     6.0
4       Emma     NaN     7.0
5      Frank     NaN     8.0

In [16]:
# keeps all records on the left dataframe and common records from the right df
pd.merge(df_3, df_4, on='Names', how='left')

       Names  Score1  Score2
0        Ama       1     NaN
1      Barry       2     5.0
2  Celestine       3     NaN
3       Dela       4     6.0

In [17]:
# keeps all records on the right dataframe and common records from the left df
pd.merge(df_3, df_4, on='Names', how='right')

   Names  Score1  Score2
0  Barry     2.0       5
1   Dela     4.0       6
2   Emma     NaN       7
3  Frank     NaN       8

In [18]:
# Merge instance on two dataframes having different column names
df_5 = pd.DataFrame({'Name1': ['Ama', 'Barry', 'Celestine', 'Dela'], 'Score': [1, 2, 3, 4]})
df_6 = pd.DataFrame({'Name2': ['Barry', 'Dela', 'Emma', 'Frank'], 'Score': [5, 6, 7, 8]})
merged_df = pd.merge(df_5, df_6, left_on='Name1', right_on='Name2', how='inner', suffixes=('_df5', '_df6'))
merged_df

   Name1  Score_df5  Name2  Score_df6
0  Barry          2  Barry          5
1   Dela          4   Dela          6

In [19]:
# Merge instance on two dataframes having different column names
df_5.merge(df_6,left_on='Name1', right_on='Name2', how='inner', suffixes=('_df5', '_df6'))

   Name1  Score_df5  Name2  Score_df6
0  Barry          2  Barry          5
1   Dela          4   Dela          6

JOIN

The join() function is used to combine two dataframes on their indexes

In [20]:
df_7 = pd.DataFrame({'value1': [1, 2, 3, 4]}, index=['A', 'B', 'C', 'D'])
df_8 = pd.DataFrame({'value2': [5, 6, 7, 8]}, index=['B', 'D', 'E', 'F'])
df_7.join(df_8, how = "outer")

   value1  value2
A     1.0     NaN
B     2.0     5.0
C     3.0     NaN
D     4.0     6.0
E     NaN     7.0
F     NaN     8.0

Filtering: Data can be filtered based on conditions.

In [21]:
df = {'name':['Magnus','Rachael','Joanna','King'],
      'gender':['Male','Female','Female','Male'],
      'age':[46,32,29,27],
      'location':['Lagos','Port Harcourt','Ottawa','Boston']}
users = pd.DataFrame(df)
filtered_users = users[users['age'] < 40]
print(filtered_users)

      name  gender  age       location
1  Rachael  Female   32  Port Harcourt
2   Joanna  Female   29         Ottawa
3     King    Male   27         Boston

Adding and Removing Columns

In [22]:
data = {'Name': ['John', 'Alice', 'Bob'],
        'Age': [30, 25, 35],
        'City': ['New York', 'Paris', 'London']}
df = pd.DataFrame(data)
print(df)

# Adding a new column
df['Gender'] = ['Male', 'Female', 'Male']
print(" ")    #spacing
print(df)

# Removing a column
df.drop('City', axis=1, inplace=True)
print(" ")    #spacing
df

    Name  Age      City
0   John   30  New York
1  Alice   25     Paris
2    Bob   35    London

    Name  Age      City  Gender
0   John   30  New York    Male
1  Alice   25     Paris  Female
2    Bob   35    London    Male

    Name  Age  Gender
0   John   30    Male
1  Alice   25  Female
2    Bob   35    Male

Grouping and Aggregation

Data can be grouped based on one or more columns and have aggregation functions perfomed on them.

In [23]:
# Creating a DataFrame from a dictionary
data = {'Num': [10, 20, 10, 20, 20, 30, 30],
        'Age': [30, 30, 25, 25, 25, 25, 35],
        'val': [50, 52, 64, 20, 50, 60, 70]}
df = pd.DataFrame(data)
print(df)

   Num  Age  val
0   10   30   50
1   20   30   52
2   10   25   64
3   20   25   20
4   20   25   50
5   30   25   60
6   30   35   70

In [24]:
# Grouping and aggregating
grouped_mean = df.groupby('Age').mean()
grouped_mean

      Num   val
Age
25   20.0  48.5
30   15.0  51.0
35   30.0  70.0

In [25]:
max_age = df.groupby('Age').max()
max_age

     Num  val
Age
25    30   64
30    20   52
35    30   70

# Handling Missing Data

Pandas provides methods for handling missing data, such as:

*   Dropping rows with missing values;

cleaned_df = df.
dropna()
*   Filling missing values with a specified values;

 filled_df = df.fillna(0)

In [26]:
data = {'A': [1, 2, None,4],
        'B': [None, 5, 6,7]}
df = pd.DataFrame(data)

# check for missing values
print(df.isnull())

       A      B
0  False   True
1  False  False
2   True  False
3  False  False

In [27]:
filled_df = df.fillna('NaN')
print(filled_df)

     A    B
0  1.0  NaN
1  2.0  5.0
2  NaN  6.0
3  4.0  7.0

In [28]:
cleaned_df = df. dropna()
cleaned_df

     A    B
1  2.0  5.0
3  4.0  7.0

# Reading Files with Pandas
Import Pandas:

*  Import the Pandas library in your Python script or Jupyter Notebook.
*  import pandas as pd





Reading CSV Files:

*   Use the read_csv() function to read data from a CSV (Comma-Separated Values) file.


**Syntax**

df = pd.read_csv('filename.csv')

Options:

sep: Specifies the delimiter (default is ,).

header: Specifies the row number to use as column names.

index_col: Specifies the column to use as the row index.

usecols: Specifies a subset of columns to read.

In [29]:
import pandas as pd

# Reading CSV file with a different delimiter
df1 = pd.read_csv("/content/drive/MyDrive/Mobile OS Usage.csv", sep=',')
print(df1.head())  # Displaying the first few rows of the DataFrame

         Date Mobile Operating System  Percent of Usage
0  2008-12-01                 Android              0.00
1  2008-12-01                     iOS             32.56
2  2008-12-01               SymbianOS             42.02
3  2008-12-01               Series 40              0.00
4  2008-12-01           BlackBerry OS              0.00

In [30]:
import pandas as pd

# File path of the Excel file
excel_file_path = "/content/drive/MyDrive/Original_Bikeshare_dataset.xlsx"

# Read the Excel file using pandas
df = pd.read_excel(excel_file_path,
                   header=0,  # Use the first row as column names
                   index_col=None,  # Do not use any column as index
                   usecols=None  # Read all columns
                   )

# Display the DataFrame
print(df)

          ID          Start Time            End Time  Trip Duration  \
0    5688089 2017-06-11 14:55:05 2017-06-11 15:08:21            795
1    4096714 2017-05-11 15:30:11 2017-05-11 15:41:43            692
2    2173887 2017-03-29 13:26:26 2017-03-29 13:48:31           1325
3    3945638 2017-05-08 19:47:18 2017-05-08 19:59:01            703
4    6208972 2017-06-21 07:49:16 2017-06-21 07:54:46            329
..       ...                 ...                 ...            ...
661  5797505 2017-06-13 13:19:01 2017-06-13 13:26:25            444
662  2010334 2017-03-23 15:29:41 2017-03-23 15:44:54            912
663  3447958 2017-04-28 18:39:51 2017-04-28 18:49:10            559
664  2854090 2017-04-15 15:56:05 2017-04-15 16:03:58            472
665  3795615 2017-05-05 00:14:46 2017-05-05 00:38:49           1443

                  Start Station                End Station   User Type  \
0       Suffolk St & Stanton St     W Broadway & Spring St  Subscriber
1       Lexington Ave & E 63 St            1 Ave & E 78 St  Subscriber
2             1 Pl & Clinton St       Henry St & Degraw St  Subscriber
3         Barrow St & Hudson St            W 20 St & 8 Ave  Subscriber
4               1 Ave & E 44 St            E 53 St & 3 Ave  Subscriber
..                          ...                        ...         ...
661       Pershing Square South         Broadway & W 36 St  Subscriber
662    W 104 St & Amsterdam Ave    Amsterdam Ave & W 73 St  Subscriber
663     Suffolk St & Stanton St      Forsyth St & Canal St  Subscriber
664       E 66 St & Madison Ave            W 52 St & 5 Ave  Subscriber
665  Richardson St & N Henry St  Putnam Ave & Nostrand Ave  Subscriber

     Gender  Birth Year   Age
0      Male      1998.0  25.0
1      Male      1981.0  42.0
2      Male      1987.0  36.0
3    Female      1986.0  37.0
4      Male      1992.0  31.0
..      ...         ...   ...
661    Male      1978.0  45.0
662    Male      1978.0  45.0
663    Male      1990.0  33.0
664    Male      1966.0  57.0
665  Female      1983.0  40.0

[666 rows x 10 columns]

In [31]:
df.head()     # displays the first five rows of the dataset

,ID,Start Time,End Time,Trip Duration,Start Station,End Station,User Type,Gender,Birth Year,Age
0,5688089,2017-06-11 14:55:05,2017-06-11 15:08:21,795,Suffolk St & Stanton St,W Broadway & Spring St,Subscriber,Male,1998.0,25.0
1,4096714,2017-05-11 15:30:11,2017-05-11 15:41:43,692,Lexington Ave & E 63 St,1 Ave & E 78 St,Subscriber,Male,1981.0,42.0
2,2173887,2017-03-29 13:26:26,2017-03-29 13:48:31,1325,1 Pl & Clinton St,Henry St & Degraw St,Subscriber,Male,1987.0,36.0
3,3945638,2017-05-08 19:47:18,2017-05-08 19:59:01,703,Barrow St & Hudson St,W 20 St & 8 Ave,Subscriber,Female,1986.0,37.0
4,6208972,2017-06-21 07:49:16,2017-06-21 07:54:46,329,1 Ave & E 44 St,E 53 St & 3 Ave,Subscriber,Male,1992.0,31.0

In [32]:
df.tail()   # displays the last five rows of the dataset

,ID,Start Time,End Time,Trip Duration,Start Station,End Station,User Type,Gender,Birth Year,Age
661,5797505,2017-06-13 13:19:01,2017-06-13 13:26:25,444,Pershing Square South,Broadway & W 36 St,Subscriber,Male,1978.0,45.0
662,2010334,2017-03-23 15:29:41,2017-03-23 15:44:54,912,W 104 St & Amsterdam Ave,Amsterdam Ave & W 73 St,Subscriber,Male,1978.0,45.0
663,3447958,2017-04-28 18:39:51,2017-04-28 18:49:10,559,Suffolk St & Stanton St,Forsyth St & Canal St,Subscriber,Male,1990.0,33.0
664,2854090,2017-04-15 15:56:05,2017-04-15 16:03:58,472,E 66 St & Madison Ave,W 52 St & 5 Ave,Subscriber,Male,1966.0,57.0
665,3795615,2017-05-05 00:14:46,2017-05-05 00:38:49,1443,Richardson St & N Henry St,Putnam Ave & Nostrand Ave,Subscriber,Female,1983.0,40.0